package com.example.pixel.enums;

public enum BookGenre {
    FANTASY, SCIENCE_FICTION, MYSTERY, THRILLER, HORROR, ROMANCE,
    HISTORICAL_FICTION, ADVENTURE, DRAMA, DYSTOPIAN, CRIME,
    MAGICAL_REALISM, LITERARY_FICTION, YOUNG_ADULT,
    BIOGRAPHY, AUTOBIOGRAPHY, MEMOIR, SELF_HELP, HISTORY,
    PHILOSOPHY, PSYCHOLOGY, SCIENCE, BUSINESS, HEALTH_FITNESS,
    TRAVEL, TRUE_CRIME, POLITICS, ESSAY
}
